### ISSUE TITLE
Підготовка

### ISSUE THREAD

**Issue by CNTGFYGSLH** [CNTGFYGSLH/bublic#1]
Обговорення поїздки в Франкфурт

**Comment by Stepan228** [comment]
Продумуємо відпочинок та витрати на нього

**Comment by CNTGFYGSLH** [comment]
Я знайшов дешевий хостел

**Comment by CNTGFYGSLH** [comment]
Знайди дешевий транспорт!!!

**Comment by Stepan228** [comment]
Знайшов декілька цікавих місць, в які нам варто зайти
